### ISSUE TITLE
Build standalone version

### ISSUE THREAD

**Issue by danielbachhuber** [banterability/dateline#1]
For developers who aren't using browserify, it would be nice to have a standalone version I could drop into a project.

https://gist.github.com/danielbachhuber/1850cfc46aa95eb54417 does the trick by removing `module.exports = Deadline;` and changing instantiation to `this.Deadline = function`.

If you think this is a good idea, I'd be happy to take a swing at adapting the `Makefile` to accommodate this.

**Comment by banterability** [comment]
@danielbachhuber Just published 2.0.0, which I think addresses your issue (`Dateline` is now exposed globally in a browser-like environment.) Let me know if there's still something uncovered by your request.

**Comment by danielbachhuber** [comment]
Awesome — thanks!

cc @eyeseast
